### ISSUE TITLE
Verificar erro do ranking

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#484]
- O ranking não está obedecendo a ordem por renda per capta (Tabela geral)
- Quando uma renda é alterada, a renda per capta não é atualizada (Tabela geral)
- Mover a coluna do ranking para a primeira posição da tabela

**Comment by allanfvc** [comment]
java.lang.NullPointerException: null
	at br.ufc.npi.auxilio.model.Inscricao.compareTo(Inscricao.java:507) ~[classes/:na]
	at br.ufc.npi.auxilio.model.Inscricao.compareTo(Inscricao.java:1) ~[classes/:na]
